# Generated by Django 5.1.5 on 2025-01-18 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_taggeditem_content_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemtag',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
